package gui.viewer;

import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 * The type Message window.
 *
 * @author Olimpia Popica
 */
public class MessageWindow extends javax.swing.JDialog {

    /**
     * Creates new form MessageWindow
     *
     * @param parent     The frame that is the parent of the window
     * @param modal      Specifies whether dialog blocks user input to other top-level windows when shown. If true, the modality type property is set to DEFAULT_MODALITY_TYPE, otherwise the dialog is modeless.
     * @param title      The name of the window
     * @param message    The message that has to be showed
     * @param buttonText The text on the button
     * @param imagePath  The image that will be showed on the left side of the panel
     */
    public MessageWindow(java.awt.Frame parent, boolean modal, String title, String message, String buttonText, String imagePath) {
        super(parent, modal);
        initComponents();

        jTAShowMessage.setText(message);
        jBButton.setText(buttonText);
        jLImage.setIcon(new ImageIcon(imagePath));
        jLImage.setText("");

        prepareFrame(parent, title);
    }

    /**
     * Creates new form MessageWindow
     *
     * @param parent     The frame that is the parent of the window
     * @param modal      Specifies whether dialog blocks user input to other top-level windows when shown. If true, the modality type property is set to DEFAULT_MODALITY_TYPE, otherwise the dialog is modeless.
     * @param title      The name of the window
     * @param message    The message that has to be showed
     * @param buttonText The text on the button
     * @param image      The image that will be showed on the left side of the panel
     */
    public MessageWindow(java.awt.Frame parent, boolean modal, String title, String message, String buttonText, Icon image) {
        super(parent, modal);
        initComponents();

        jTAShowMessage.setText(message);
        jBButton.setText(buttonText);
        jLImage.setIcon(image);
        jLImage.setText("");

        prepareFrame(parent, title);
    }

    /**
     * Code related to the frame like: pack, set location etc.
     */
    private void prepareFrame(java.awt.Frame parent, String title) {
        setTitle(title);

        this.setResizable(false);

        this.pack();

        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jBButton = new javax.swing.JButton();
        jLImage = new javax.swing.JLabel();
        jTAShowMessage = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jBButton.setText("OK");
        jBButton.setPreferredSize(new java.awt.Dimension(70, 23));
        jBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 10, 5);
        jPanel1.add(jBButton, gridBagConstraints);

        jLImage.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.01;
        gridBagConstraints.weighty = 0.01;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanel1.add(jLImage, gridBagConstraints);

        jTAShowMessage.setEditable(false);
        jTAShowMessage.setColumns(20);
        jTAShowMessage.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTAShowMessage.setRows(5);
        jTAShowMessage.setTabSize(4);
        jTAShowMessage.setWrapStyleWord(true);
        jTAShowMessage.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 5, 10);
        jPanel1.add(jTAShowMessage, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBButtonActionPerformed
        MessageWindow.this.dispose();
    }//GEN-LAST:event_jBButtonActionPerformed

    /**
     * The entry point of application.
     *
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MessageWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            MessageWindow dialog = new MessageWindow(new javax.swing.JFrame(), true, "Test Window", "The message to be displayed!", "Agree", common.Icons.EXCLAMATION_ICON_PATH);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBButton;
    private javax.swing.JLabel jLImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTAShowMessage;
    // End of variables declaration//GEN-END:variables
}
